### ISSUE TITLE
Error messages to be more informative for CSV Photometry Upload

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#124] opened 2024-03-23 10:06 UTC
CSV photometry upload could check for possible errors, and give a more detailed message.
Let's list the possible errors here and then code them:
1. File has the wrong format (check if JD is used or MJD, and if all the columns are there and the header)
2. File should have the .csv extension
3. ... add more if encountered

**Comment by YuriiPurdenko** [comment] 2024-08-12 08:56
It seems to be a duplicate of that issue https://github.com/BHTOM-Team/bhtom2-uploadService/issues/5

**Closed** 2024-10-17 11:35 UTC
Labels: enhancement
